-- Q1: Error-rate time series in 1-minute buckets.
-- Transparent aggregation over the high-volume LOGS table.
SELECT
    SERVICE_ID,
    TRUNC(TS, 'MI') AS MINUTE_BUCKET,
    COUNT(*) AS TOTAL_LOGS,
    SUM(CASE WHEN LEVEL = 'ERROR' THEN 1 ELSE 0 END) AS ERROR_COUNT,
    ROUND(100.0 * SUM(CASE WHEN LEVEL = 'ERROR' THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS ERROR_RATE_PCT
FROM DEPLOY_DETECTIVE.LOGS
WHERE SERVICE_ID = :service_id
GROUP BY SERVICE_ID, TRUNC(TS, 'MI')
ORDER BY MINUTE_BUCKET;

-- Q2: Temporal correlation of a deploy with an error-rate spike.
-- A moving baseline is computed with an analytic window function in Exasol.
WITH minute_errors AS (
    SELECT
        SERVICE_ID,
        TRUNC(TS, 'MI') AS MINUTE_BUCKET,
        1.0 * SUM(CASE WHEN LEVEL = 'ERROR' THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS ERROR_RATE
    FROM DEPLOY_DETECTIVE.LOGS
    WHERE SERVICE_ID = :service_id
    GROUP BY SERVICE_ID, TRUNC(TS, 'MI')
), ranked AS (
    SELECT
        SERVICE_ID,
        MINUTE_BUCKET,
        ERROR_RATE,
        AVG(ERROR_RATE) OVER (
            PARTITION BY SERVICE_ID
            ORDER BY MINUTE_BUCKET
            ROWS BETWEEN 10 PRECEDING AND 1 PRECEDING
        ) AS BASELINE_RATE
    FROM minute_errors
)
SELECT
    d.DEPLOY_ID,
    d.SERVICE_ID,
    d.DEPLOYED_AT,
    d.VERSION,
    r.MINUTE_BUCKET,
    ROUND(100.0 * r.ERROR_RATE, 2) AS ERROR_RATE_PCT,
    ROUND(100.0 * COALESCE(r.BASELINE_RATE, 0), 2) AS BASELINE_RATE_PCT,
    ROUND(100.0 * (r.ERROR_RATE - COALESCE(r.BASELINE_RATE, 0)), 2) AS SPIKE_DELTA_PCT,
    ABS(POSIX_TIME(r.MINUTE_BUCKET) - POSIX_TIME(d.DEPLOYED_AT)) / 60 AS MINUTES_FROM_DEPLOY
FROM ranked r
JOIN DEPLOY_DETECTIVE.DEPLOYS d
  ON d.SERVICE_ID = r.SERVICE_ID
 AND r.MINUTE_BUCKET BETWEEN d.DEPLOYED_AT AND d.DEPLOYED_AT + INTERVAL '30' MINUTE
WHERE r.ERROR_RATE > COALESCE(r.BASELINE_RATE, 0) * 3
ORDER BY SPIKE_DELTA_PCT DESC, MINUTES_FROM_DEPLOY ASC;

-- Q3: Downstream p95 latency in the 10 minutes after each candidate deploy.
SELECT
    d.DEPLOY_ID,
    d.VERSION,
    d.DEPLOYED_AT,
    m.SERVICE_ID AS DOWNSTREAM_SERVICE_ID,
    ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY m.VALUE), 2) AS P95_LATENCY_MS,
    s.SERVICE_NAME AS DOWNSTREAM_SERVICE
FROM DEPLOY_DETECTIVE.DEPLOYS d
JOIN DEPLOY_DETECTIVE.SERVICES owner
  ON owner.SERVICE_ID = d.SERVICE_ID
JOIN DEPLOY_DETECTIVE.SERVICES s
  ON s.SERVICE_ID = owner.DEPENDS_ON
JOIN DEPLOY_DETECTIVE.METRICS m
  ON m.SERVICE_ID = s.SERVICE_ID
 AND m.METRIC_NAME = 'p95_latency_ms'
 AND m.TS BETWEEN d.DEPLOYED_AT AND d.DEPLOYED_AT + INTERVAL '10' MINUTE
WHERE d.SERVICE_ID = :service_id
  AND (:deploy_id = '' OR d.DEPLOY_ID = :deploy_id)
GROUP BY d.DEPLOY_ID, d.VERSION, d.DEPLOYED_AT, m.SERVICE_ID, s.SERVICE_NAME
ORDER BY d.DEPLOYED_AT DESC;

-- Q4: Historical incidents for this service, with their known root-cause deploy.
SELECT
    i.INCIDENT_ID,
    i.SERVICE_ID,
    i.OPENED_AT,
    i.RESOLVED_AT,
    i.ROOT_CAUSE_DEPLOY_ID,
    d.VERSION AS ROOT_CAUSE_VERSION,
    i.TITLE,
    i.STATUS
FROM DEPLOY_DETECTIVE.INCIDENTS i
LEFT JOIN DEPLOY_DETECTIVE.DEPLOYS d
  ON d.DEPLOY_ID = i.ROOT_CAUSE_DEPLOY_ID
WHERE i.SERVICE_ID = :service_id
ORDER BY i.OPENED_AT DESC;

-- Q5: Verify recovery after the recorded action.
-- No recovery rows are written by this query. It only reads observed replay telemetry.
SELECT
    a.ACTION_ID,
    a.ACTIONED_AT,
    a.ACTION_TYPE,
    ROUND(100.0 * AVG(CASE WHEN m.TS < a.ACTIONED_AT THEN m.VALUE ELSE NULL END), 2) AS PRE_ERROR_RATE_PCT,
    ROUND(100.0 * AVG(CASE WHEN m.TS >= a.ACTIONED_AT THEN m.VALUE ELSE NULL END), 2) AS POST_ERROR_RATE_PCT,
    ROUND(
        100.0 * (
            AVG(CASE WHEN m.TS < a.ACTIONED_AT THEN m.VALUE ELSE NULL END)
            - AVG(CASE WHEN m.TS >= a.ACTIONED_AT THEN m.VALUE ELSE NULL END)
        ), 2
    ) AS IMPROVEMENT_PCT_POINTS
FROM DEPLOY_DETECTIVE.AGENT_ACTIONS a
JOIN DEPLOY_DETECTIVE.METRICS m
  ON m.SERVICE_ID = a.SERVICE_ID
 AND m.METRIC_NAME = 'error_rate'
 AND m.TS BETWEEN a.ACTIONED_AT - INTERVAL '10' MINUTE AND a.ACTIONED_AT + INTERVAL '10' MINUTE
WHERE a.ACTION_ID = :action_id
GROUP BY a.ACTION_ID, a.ACTIONED_AT, a.ACTION_TYPE;
