CREATE SCHEMA IF NOT EXISTS DEPLOY_DETECTIVE;
OPEN SCHEMA DEPLOY_DETECTIVE;

DROP VIEW IF EXISTS CURRENT_SERVICE_HEALTH;
DROP VIEW IF EXISTS INCIDENT_OVERVIEW;
DROP TABLE IF EXISTS SCENARIO_EVENTS;
DROP TABLE IF EXISTS AGENT_ACTIONS;
DROP TABLE IF EXISTS INCIDENTS;
DROP TABLE IF EXISTS METRICS;
DROP TABLE IF EXISTS LOGS;
DROP TABLE IF EXISTS DEPLOYS;
DROP TABLE IF EXISTS SERVICES;

CREATE TABLE SERVICES (
    SERVICE_ID VARCHAR(64) NOT NULL,
    SERVICE_NAME VARCHAR(128) NOT NULL,
    TEAM VARCHAR(128),
    DEPENDS_ON VARCHAR(64),
    PRIMARY KEY (SERVICE_ID)
);

CREATE TABLE DEPLOYS (
    DEPLOY_ID VARCHAR(64) NOT NULL,
    SERVICE_ID VARCHAR(64) NOT NULL,
    DEPLOYED_AT TIMESTAMP NOT NULL,
    VERSION VARCHAR(64) NOT NULL,
    AUTHOR VARCHAR(128),
    CHANGE_SUMMARY VARCHAR(500),
    STATUS VARCHAR(32) DEFAULT 'ACTIVE',
    PRIMARY KEY (DEPLOY_ID)
);

CREATE TABLE LOGS (
    LOG_ID DECIMAL(20,0) NOT NULL,
    SERVICE_ID VARCHAR(64) NOT NULL,
    TS TIMESTAMP NOT NULL,
    LEVEL VARCHAR(16) NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL
);

CREATE TABLE METRICS (
    SERVICE_ID VARCHAR(64) NOT NULL,
    TS TIMESTAMP NOT NULL,
    METRIC_NAME VARCHAR(64) NOT NULL,
    VALUE DOUBLE NOT NULL
);

CREATE TABLE INCIDENTS (
    INCIDENT_ID VARCHAR(64) NOT NULL,
    SERVICE_ID VARCHAR(64) NOT NULL,
    OPENED_AT TIMESTAMP NOT NULL,
    RESOLVED_AT TIMESTAMP,
    ROOT_CAUSE_DEPLOY_ID VARCHAR(64),
    TITLE VARCHAR(300),
    STATUS VARCHAR(32),
    PRIMARY KEY (INCIDENT_ID)
);

CREATE TABLE AGENT_ACTIONS (
    ACTION_ID VARCHAR(64) NOT NULL,
    INCIDENT_ID VARCHAR(64) NOT NULL,
    SERVICE_ID VARCHAR(64) NOT NULL,
    ACTION_TYPE VARCHAR(64) NOT NULL,
    TARGET_DEPLOY_ID VARCHAR(64),
    ACTIONED_AT TIMESTAMP NOT NULL,
    RESULT VARCHAR(64) NOT NULL,
    DETAILS VARCHAR(1000),
    PRIMARY KEY (ACTION_ID)
);

CREATE TABLE SCENARIO_EVENTS (
    EVENT_ID VARCHAR(64) NOT NULL,
    INCIDENT_ID VARCHAR(64),
    SERVICE_ID VARCHAR(64) NOT NULL,
    EVENT_TS TIMESTAMP NOT NULL,
    EVENT_TYPE VARCHAR(64) NOT NULL,
    DETAILS VARCHAR(1000),
    PRIMARY KEY (EVENT_ID)
);

CREATE VIEW INCIDENT_OVERVIEW AS
SELECT
    i.INCIDENT_ID,
    i.SERVICE_ID,
    s.SERVICE_NAME,
    i.OPENED_AT,
    i.RESOLVED_AT,
    i.ROOT_CAUSE_DEPLOY_ID,
    d.VERSION AS ROOT_CAUSE_VERSION,
    i.TITLE,
    i.STATUS
FROM INCIDENTS i
JOIN SERVICES s ON s.SERVICE_ID = i.SERVICE_ID
LEFT JOIN DEPLOYS d ON d.DEPLOY_ID = i.ROOT_CAUSE_DEPLOY_ID;

CREATE VIEW CURRENT_SERVICE_HEALTH AS
SELECT
    m.SERVICE_ID,
    MAX(CASE WHEN m.METRIC_NAME = 'error_rate' THEN m.VALUE ELSE NULL END) AS LATEST_ERROR_RATE,
    MAX(CASE WHEN m.METRIC_NAME = 'p95_latency_ms' THEN m.VALUE ELSE NULL END) AS LATEST_P95_LATENCY_MS
FROM METRICS m
GROUP BY m.SERVICE_ID;
